### PR TITLE
Fix currency display quantities

### PR DESCRIPTION
**Pull request by Mctalian**
Some currencies (mainly PvP currencies like Conquest or Bloody Tokens) have an assumed precision on the API side. The actual stored quantity will be 5000 but the value displayed to the player in all scenarios will be 50.

I don't think `GetBasicCurrencyInfo` is included in `C_Everywhere` so this likely needs more work before it can just be merged, but I wanted to propose a potential fix that we can work on together. I'm happy to look at adding the function to `C_Everywhere` library as well.

### CODE REVIEW

**Comment by Jaliborc** [comment]
Didn't know about his, thank you for pointing it out. Will gonna have to do some experiments on GetBasicCurrencyInfo first, but looks good.
Do you happen to have the IDs of Conquest / Bloody Tokens?

**Comment by Mctalian** [comment]
> Didn't know about his, thank you for pointing it out. Will gonna have to do some experiments on GetBasicCurrencyInfo first, but looks good.
> Do you happen to have the IDs of Conquest / Bloody Tokens?

Sure! 

https://www.wowhead.com/currency=2123/bloody-tokens

2123 for BTs

https://www.wowhead.com/currency=1602/conquest

1602 for Conquest

**Comment by Mctalian** [comment]
👋🏻 anything I can do to help get this in? If it helps, I use this functionality in RPGLootFeed for when I display currency, it mainly only impacts PvP currencies, though.

**Comment by Jaliborc** [comment]
Sorry for the delay, I've just been extremely busy getting used to my new
job, haven't been able to look at the mods. Will hopefully do so starting
this or next week.

**Comment by Mctalian** [comment]
No worries! I can relate, I just started a new job too - I just wanted to check in. Let me know if I can help out in any way and good luck on your new job 👍

**Comment by Jaliborc** [comment]
So, if I am understanding this correctly, does GetBackpackCurrencyInfo return the correct "display amount" for these currencies, but on CURRENCY_DISPLAY_UPDATE they are reported incorrectly?

**Comment by Jaliborc** [comment]
> 👋🏻 anything I can do to help get this in? If it helps, I use this functionality in RPGLootFeed for when I display currency, it mainly only impacts PvP currencies, though.

Could you please let me know what you get when you type:
```
/dump C_CurrencyInfo.GetCurrencyInfo(2123).quantity
/dump C_CurrencyInfo.GetCurrencyInfo(1602).quantity
```

Don't have a maxed out character on retail, so can't get conquest to try it myself. Do you get the actual quantity here from that function, or the display quantity? Done some testing on classic, and the current solution could cause some issues with the honor there.

**Comment by Mctalian** [comment]
Sure I'll take a look today

**Comment by Mctalian** [comment]
I see what you mean about Honor. I haven't been PVPing so I can't get those Quantity values you're asking for, but I have an idea on how to update this PR to make it more tolerant of these things.

**Comment by Mctalian** [comment]
Actually, nevermind, I see no issue with Honor:
image

You have to remember to pass in the quantity as the second argument to GetBasicCurrencyInfo so that it can convert the quantity to the displayAmount.

I'll try to get some Conquest or Bloody Tokens this weekend to provide that data which should help clarify this.

**Comment by Mctalian** [comment]
Ok now I remember, you are correct, it's an issue with CURRENCY_DISPLAY_UPDATE in particular:
image

I still think the PR is valid, but I apologize for the confusion!

**Comment by Jaliborc** [comment]
The issue with honor is on classic servers, not retail. On cataclysm servers, for some reason, GetBasicCurrencyInfo reduces the amount of honor, as if they were conquest points.

But GetCurrencyInfo appears to be returning correct values on all servers and currencies, so we can just use that!

**Comment by Mctalian** [comment]
Yeah that makes sense, I'll make that change in a bit

**Pull request merged**
